/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeritBadgesIndexRouteImport } from './routes/merit-badges/index'
import { Route as MeritBadgesBadgeIdRouteImport } from './routes/merit-badges/$badgeId'
import { Route as ApiUserDataRouteImport } from './routes/api/user-data'
import { Route as ApiUserRouteImport } from './routes/api/user'
import { Route as ApiAiCoachRouteImport } from './routes/api/ai-coach'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeritBadgesIndexRoute = MeritBadgesIndexRouteImport.update({
  id: '/merit-badges/',
  path: '/merit-badges/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeritBadgesBadgeIdRoute = MeritBadgesBadgeIdRouteImport.update({
  id: '/merit-badges/$badgeId',
  path: '/merit-badges/$badgeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserDataRoute = ApiUserDataRouteImport.update({
  id: '/api/user-data',
  path: '/api/user-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRoute = ApiUserRouteImport.update({
  id: '/api/user',
  path: '/api/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCoachRoute = ApiAiCoachRouteImport.update({
  id: '/api/ai-coach',
  path: '/api/ai-coach',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/api/ai-coach': typeof ApiAiCoachRoute
  '/api/user': typeof ApiUserRoute
  '/api/user-data': typeof ApiUserDataRoute
  '/merit-badges/$badgeId': typeof MeritBadgesBadgeIdRoute
  '/merit-badges': typeof MeritBadgesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/api/ai-coach': typeof ApiAiCoachRoute
  '/api/user': typeof ApiUserRoute
  '/api/user-data': typeof ApiUserDataRoute
  '/merit-badges/$badgeId': typeof MeritBadgesBadgeIdRoute
  '/merit-badges': typeof MeritBadgesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/api/ai-coach': typeof ApiAiCoachRoute
  '/api/user': typeof ApiUserRoute
  '/api/user-data': typeof ApiUserDataRoute
  '/merit-badges/$badgeId': typeof MeritBadgesBadgeIdRoute
  '/merit-badges/': typeof MeritBadgesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/api/ai-coach'
    | '/api/user'
    | '/api/user-data'
    | '/merit-badges/$badgeId'
    | '/merit-badges'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/api/ai-coach'
    | '/api/user'
    | '/api/user-data'
    | '/merit-badges/$badgeId'
    | '/merit-badges'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/api/ai-coach'
    | '/api/user'
    | '/api/user-data'
    | '/merit-badges/$badgeId'
    | '/merit-badges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAiCoachRoute: typeof ApiAiCoachRoute
  ApiUserRoute: typeof ApiUserRoute
  ApiUserDataRoute: typeof ApiUserDataRoute
  MeritBadgesBadgeIdRoute: typeof MeritBadgesBadgeIdRoute
  MeritBadgesIndexRoute: typeof MeritBadgesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merit-badges/': {
      id: '/merit-badges/'
      path: '/merit-badges'
      fullPath: '/merit-badges'
      preLoaderRoute: typeof MeritBadgesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merit-badges/$badgeId': {
      id: '/merit-badges/$badgeId'
      path: '/merit-badges/$badgeId'
      fullPath: '/merit-badges/$badgeId'
      preLoaderRoute: typeof MeritBadgesBadgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user-data': {
      id: '/api/user-data'
      path: '/api/user-data'
      fullPath: '/api/user-data'
      preLoaderRoute: typeof ApiUserDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user': {
      id: '/api/user'
      path: '/api/user'
      fullPath: '/api/user'
      preLoaderRoute: typeof ApiUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-coach': {
      id: '/api/ai-coach'
      path: '/api/ai-coach'
      fullPath: '/api/ai-coach'
      preLoaderRoute: typeof ApiAiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAiCoachRoute: ApiAiCoachRoute,
  ApiUserRoute: ApiUserRoute,
  ApiUserDataRoute: ApiUserDataRoute,
  MeritBadgesBadgeIdRoute: MeritBadgesBadgeIdRoute,
  MeritBadgesIndexRoute: MeritBadgesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
