/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AiCoachRouteImport } from './routes/ai-coach'
import { Route as AdvancementRouteImport } from './routes/advancement'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeritBadgesIndexRouteImport } from './routes/merit-badges/index'
import { Route as MeritBadgesBadgeIdRouteImport } from './routes/merit-badges/$badgeId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCoachRoute = AiCoachRouteImport.update({
  id: '/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancementRoute = AdvancementRouteImport.update({
  id: '/advancement',
  path: '/advancement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeritBadgesIndexRoute = MeritBadgesIndexRouteImport.update({
  id: '/merit-badges/',
  path: '/merit-badges/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeritBadgesBadgeIdRoute = MeritBadgesBadgeIdRouteImport.update({
  id: '/merit-badges/$badgeId',
  path: '/merit-badges/$badgeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advancement': typeof AdvancementRoute
  '/ai-coach': typeof AiCoachRoute
  '/events': typeof EventsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/merit-badges/$badgeId': typeof MeritBadgesBadgeIdRoute
  '/merit-badges': typeof MeritBadgesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advancement': typeof AdvancementRoute
  '/ai-coach': typeof AiCoachRoute
  '/events': typeof EventsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/merit-badges/$badgeId': typeof MeritBadgesBadgeIdRoute
  '/merit-badges': typeof MeritBadgesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advancement': typeof AdvancementRoute
  '/ai-coach': typeof AiCoachRoute
  '/events': typeof EventsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/merit-badges/$badgeId': typeof MeritBadgesBadgeIdRoute
  '/merit-badges/': typeof MeritBadgesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advancement'
    | '/ai-coach'
    | '/events'
    | '/onboarding'
    | '/profile'
    | '/merit-badges/$badgeId'
    | '/merit-badges'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advancement'
    | '/ai-coach'
    | '/events'
    | '/onboarding'
    | '/profile'
    | '/merit-badges/$badgeId'
    | '/merit-badges'
  id:
    | '__root__'
    | '/'
    | '/advancement'
    | '/ai-coach'
    | '/events'
    | '/onboarding'
    | '/profile'
    | '/merit-badges/$badgeId'
    | '/merit-badges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancementRoute: typeof AdvancementRoute
  AiCoachRoute: typeof AiCoachRoute
  EventsRoute: typeof EventsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  MeritBadgesBadgeIdRoute: typeof MeritBadgesBadgeIdRoute
  MeritBadgesIndexRoute: typeof MeritBadgesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-coach': {
      id: '/ai-coach'
      path: '/ai-coach'
      fullPath: '/ai-coach'
      preLoaderRoute: typeof AiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advancement': {
      id: '/advancement'
      path: '/advancement'
      fullPath: '/advancement'
      preLoaderRoute: typeof AdvancementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merit-badges/': {
      id: '/merit-badges/'
      path: '/merit-badges'
      fullPath: '/merit-badges'
      preLoaderRoute: typeof MeritBadgesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merit-badges/$badgeId': {
      id: '/merit-badges/$badgeId'
      path: '/merit-badges/$badgeId'
      fullPath: '/merit-badges/$badgeId'
      preLoaderRoute: typeof MeritBadgesBadgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancementRoute: AdvancementRoute,
  AiCoachRoute: AiCoachRoute,
  EventsRoute: EventsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  MeritBadgesBadgeIdRoute: MeritBadgesBadgeIdRoute,
  MeritBadgesIndexRoute: MeritBadgesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
